all:
	../sys/bgfx/.build/linux64_gcc/bin/shadercRelease -f vs_triangle.sc -o vs_triangle.bin -p spirv --type vertex
	../sys/bgfx/.build/linux64_gcc/bin/shadercRelease -f fs_triangle.sc -o fs_triangle.bin -p spirv --type fragment